#!/usr/bin/perl
use 5.020;
use experimental 'signatures';

use Getopt::Long;
use Pod::Usage;
use RecentInfo::Manager 'recent_files';
use PerlX::Maybe;
use URI;
use URI::file;

GetOptions(
    'f|file=s'     => \my $filename,
    'a|app=s'      => \my $app,
    't|mimetype=s' => \my $mimetype,
    'n|count=s'    => \my $count,
    'native'       => \my $native,
) or pod2usage(2);

$count //= 10;

my @res = recent_files({
    maybe app => $app,
    maybe mime_type => $mimetype,
}, {
    maybe filename => $filename,
});

if( $count and @res ) {
    @res = splice @res, -$count;
}

# native should be the default?!
if( $native ) {
    @res = map {
        m!^file:! ? URI->new( $_ )->file : $_
    } @res;
}

say $_ for @res;
