#!/usr/bin/perl
use 5.020;
use experimental 'signatures';

use Getopt::Long;
use Pod::Usage;
use RecentInfo::Manager 'recent_files';
use PerlX::Maybe;
use URI;
use URI::file;

GetOptions(
    'f|file=s'     => \my $filename,
    'a|app=s'      => \my $app,
    't|mimetype=s' => \my $mimetype,
    'n|count=s'    => \my $count,
    'b|below:s'    => \my $below,
) or pod2usage(2);

$count //= 10;

if( defined $below ) {
    $below ||= '.';
    $below = File::Spec->rel2abs( $below );
}
my @res = recent_files({
    maybe app => $app,
    maybe mime_type => $mimetype,
}, {
    maybe filename => $filename,
});

if( $below ) {
    @res = grep { m!\A\Q$below! } @res;
};

if( $count and @res ) {
    @res = splice @res, -$count;
}

say $_ for @res;
